name: actions-testing
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: try-it-out/tryit-docker-action@v1.11
        with:
          event-data: "${{ toJSON(github.event) }}"
          github-api-token: '${{ secrets.GH_API_TOKEN }}'
          twitter-api-token: '${{ secrets.IFTT_KEY }}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
