name: actions-testing
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: try-it-out/tryit-docker-action@v1.10
        with:
          who-to-greet: 'Vasilii'
          event-data: "${{ toJSON(github.event) }}"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
